"""Trace the round logo into the assets the site and the intro use.

Run: python3 scripts/trace-logo.py
Needs: numpy, opencv-python-headless, scikit-image, potracer

Writes
  src/brand/logo-path.ts  the monogram as one filled SVG path (viewBox 0 0 640 520)
  src/brand/logo-flow.png the "ink flow" map: for every pixel of the monogram, how far
                          ink has to travel along the strokes from the bottom of the
                          teardrop. 16-bit, packed as red = high byte, green = low byte.
"""
from pathlib import Path
import numpy as np
import cv2
import potrace
from skimage.graph import MCP_Geometric

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets-src" / "logo-source.jpg"
S = 4                      # trace at 4x for smooth curves
OX, OY, W, H = 53, 150, 640, 520   # crop of the source, in source pixels
CENTER, RADIUS = (385, 388), 330   # inside the round badge

im = cv2.imread(str(SRC)).astype(np.float32)
h, w = im.shape[:2]
big = cv2.resize(im, (w * S, h * S), interpolation=cv2.INTER_CUBIC)
lum = 0.299 * big[..., 2] + 0.587 * big[..., 1] + 0.114 * big[..., 0]
yy, xx = np.mgrid[0 : h * S, 0 : w * S]
inside = (xx - CENTER[0] * S) ** 2 + (yy - CENTER[1] * S) ** 2 < (RADIUS * S) ** 2
mask = ((lum < 185) & inside).astype(np.uint8) * 255
mask = (cv2.GaussianBlur(mask, (0, 0), 3.0) > 127)
crop = mask[OY * S : (OY + H) * S, OX * S : (OX + W) * S]

# 1. Vector fill.
plist = potrace.Bitmap(~crop).trace(turdsize=20, alphamax=1.2, opticurve=True, opttolerance=0.4)
fmt = lambda p: f"{p.x / S:.1f} {p.y / S:.1f}"
parts = []
for c in plist:
    d = [f"M{fmt(c.start_point)}"]
    for s in c.segments:
        d.append(f"L{fmt(s.c)}L{fmt(s.end_point)}" if s.is_corner else f"C{fmt(s.c1)} {fmt(s.c2)} {fmt(s.end_point)}")
    parts.append("".join(d) + "Z")
(ROOT / "src" / "brand" / "logo-path.ts").write_text(
    "// Generated by scripts/trace-logo.py from assets-src/logo-source.jpg. Do not edit by hand.\n"
    f"export const LOGO_VIEWBOX = {{ width: {W}, height: {H} }}\n"
    f"export const LOGO_PATH =\n  '{''.join(parts)}'\n"
)

# 2. Ink-flow map: geodesic distance along the strokes from the lowest point.
R = 2
c2 = cv2.resize(crop.astype(np.uint8) * 255, (W * R, H * R), interpolation=cv2.INTER_AREA) > 127
# Strokes pass under each other with small gaps; let the ink hop those gaps, at a cost.
k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
domain = cv2.dilate(c2.astype(np.uint8), k) > 0
cost = np.where(c2, 1.0, np.where(domain, 4.0, np.inf))
ys, xs = np.nonzero(c2)
seed = (ys[np.argmax(ys)], xs[np.argmax(ys)])
dist, _ = MCP_Geometric(cost).find_costs([seed])
ok = np.isfinite(dist) & domain
norm = np.where(ok, dist / dist[ok].max(), 1.0)
norm = cv2.resize(norm, (W, H), interpolation=cv2.INTER_AREA)
v = np.clip(np.round(norm * 65535), 0, 65535).astype(np.uint32)
png = np.zeros((H, W, 3), np.uint8)
png[..., 2] = (v >> 8) & 255
png[..., 1] = v & 255
cv2.imwrite(str(ROOT / "src" / "brand" / "logo-flow.png"), png, [cv2.IMWRITE_PNG_COMPRESSION, 9])
print("paths", len(plist), "seed", seed)
